import {test} from 'node:test';import assert from 'node:assert/strict';import {enrichPoint} from '../lib/geography-core.mjs';
const poly={type:'Polygon',coordinates:[[[-3.7,40.4],[-3.68,40.4],[-3.68,40.42],[-3.7,40.42],[-3.7,40.4]]]};
const base={bbox:[40.3,-3.85,40.6,-3.5],neighborhoods:[{name:'Aeropuerto',district:'Test',geometry:poly}],pois:[],facilities:[{id:'way/1',name:'Real facility',tags:{aeroway:'terminal'},geometry:poly,coordinates:[40.41,-3.69]}]};
test('terminal membership works more than 400m from center without moving coordinates',()=>{const point=[40.401,-3.699];const p=enrichPoint(point,base);assert.deepEqual(p.coordinates,point);assert.ok(p.facility_context.matches.some(f=>f.type==='airport_terminal'&&f.relation==='inside'&&f.distance_m===0));});
test('district name alone is not airport evidence',()=>{const p=enrichPoint([40.41,-3.69],{...base,facilities:[]});assert.equal(p.airport,false);assert.deepEqual(p.facility_context.matches,[]);});
test('hospital campus containment and edge proximity are distinguished',()=>{const d={...base,facilities:[{...base.facilities[0],tags:{amenity:'hospital'}}]};assert.equal(enrichPoint([40.401,-3.699],d).facility_context.matches[0].relation,'inside');const p=enrichPoint([40.3995,-3.69],d);assert.equal(p.facility_context.matches[0].relation,'nearby');assert.ok(p.facility_context.matches[0].distance_m>50&&p.facility_context.matches[0].distance_m<60);});
test('ordinary bus stops, pharmacies and metro stations do not become hubs or hospitals',()=>{for(const tags of [{highway:'bus_stop'},{amenity:'pharmacy'},{railway:'station',station:'subway'}]){const p=enrichPoint([40.41,-3.69],{...base,facilities:[{...base.facilities[0],tags}]});assert.deepEqual(p.facility_context.matches,[]);}});
test('polygon hole has no false facility membership and missing snapshot is explicit',()=>{const g=structuredClone(poly);g.coordinates.push([[-3.698,40.402],[-3.682,40.402],[-3.682,40.418],[-3.698,40.418],[-3.698,40.402]]);const p=enrichPoint([40.41,-3.69],{...base,facilities:[{...base.facilities[0],geometry:g}]});assert.ok(!p.facility_context.matches.some(m=>m.relation==='inside'));assert.equal(enrichPoint([40.41,-3.69],null).facility_context.status,'unavailable');});

test('Ciudad Universitaria surfaces verified university containment before nearby cafes',async()=>{const {readFileSync}=await import('node:fs');const data=JSON.parse(readFileSync(new URL('../public/data/geography.json',import.meta.url)));const point=enrichPoint([40.4489,-3.7294],data);const university=point.facility_context.important_pois.find(p=>p.name==='Ciudad Universitaria');assert.equal(university?.type,'education');assert.equal(university?.relation,'inside');assert.ok(point.facility_context.important_pois.some(p=>p.name?.includes('Facultad de Filología')));});

test('hospital farther than 100m excluded from functional context',()=>{const d={...base,facilities:[{...base.facilities[0],tags:{amenity:'hospital'}}]};assert.deepEqual(enrichPoint([40.399,-3.69],d).facility_context.matches,[]);});
