import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {prepare,normalize} from '../lib/jev.mjs';import {defaultCategories} from '../lib/categories.mjs';
const fixture=()=>JSON.parse(readFileSync(new URL('./fixtures/provider-six.json',import.meta.url)));
const input={trips:[{current_trip:{request_local_datetime:'2026-09-23T10:20',origin:{coordinates:[40.4503,-3.6925]},destination:{coordinates:[40.4778,-3.6888]}}}]};
test('provider receives seven concise independent trip-purpose options',()=>{const q=prepare(input).questions.demo_purpose;assert.deepEqual(Object.keys(q.criteria),['commuting','business','leisure','event_attendance','visitor_activity','other','transport_connection']);assert.equal(defaultCategories.find(category=>category.id==='visitor_activity').label,'Attraction');assert.equal(defaultCategories.find(category=>category.id==='commuting').description,'A routine, repeated journey to or from a regular workplace, campus, school, or home. It reflects an everyday work-or-study pattern and can be more plausible for weekday travel connecting residential and work or education contexts.');assert.ok(defaultCategories.every(category=>category.description.length>90&&category.description.match(/[.!?]/g)?.length===2));const labels=defaultCategories.map(category=>category.label);for(const category of defaultCategories){const otherLabels=labels.filter(label=>label!==category.label).map(label=>label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));assert.doesNotMatch(category.description,new RegExp(`\\b(?:${otherLabels.join('|')})\\b`,'i'));}assert.match(q.criteria.commuting,/routine|repeated/i);assert.match(q.criteria.business,/commercial|office|professional/i);assert.match(q.criteria.leisure,/dining|nightlife/i);assert.match(q.criteria.event_attendance,/event|concert|sport/i);assert.match(q.criteria.visitor_activity,/sightseeing|visitor/i);assert.match(q.criteria.transport_connection,/airport|intercity/i);assert.match(q.criteria.other,/not uncertainty/i);});
test('low-probability winning motive and low confidence remain unchanged',()=>{const out=fixture();const result=normalize(out,prepare(input)).cases[0].purpose;assert.equal(result.label,'commuting');assert.equal(result.probability,.25);assert.equal(result.confidence,.12);assert.deepEqual(result.probabilities,out.answers.demo_purpose.probabilities);});
test('obsolete category rejected as choice or seventh probability',()=>{const out=fixture();out.answers.demo_purpose.choice='indeterminado';assert.throws(()=>normalize(out,prepare(input)));out.answers.demo_purpose.choice='commuting';out.answers.demo_purpose.probabilities.indeterminado=0;assert.throws(()=>normalize(out,prepare(input)));});
test('tied top choices valid; non-top choice rejected',()=>{const out=fixture();out.answers.demo_purpose.probabilities={commuting:1/7,business:1/7,leisure:1/7,event_attendance:1/7,visitor_activity:1/7,other:1/7,transport_connection:1/7};out.answers.demo_purpose.choice='other';assert.equal(normalize(out).cases[0].purpose.probability,1/7);const bad=fixture();bad.answers.demo_purpose.choice='other';assert.throws(()=>normalize(bad));});
test('willingness to pay describes accepting this ride at a higher price',()=>{const q=prepare(input).questions.demo_willingness_to_pay;assert.match(q.instructions,/accept.*ride.*higher price/i);assert.match(q.instructions,/cheaper.*public transport|public transport.*cheaper/i);assert.match(q.instructions,/another.*provider|competitor/i);assert.match(q.criteria[0],/reject|cheaper/i);assert.match(q.criteria[1],/accept.*higher price/i);});
test('willingness to wait describes cancelling a requested car after a long pickup',()=>{const q=prepare(input).questions.demo_willingness_to_wait;assert.match(q.instructions,/requested car/i);assert.match(q.instructions,/cancel/i);assert.match(q.instructions,/pickup.*too long|taking too long.*pickup/i);assert.match(q.criteria[0],/cancel/i);assert.match(q.criteria[1],/keep.*before cancelling/i);});
