import {randomizeAndEvaluate} from './actions.mjs';
import {defaultCategories,validateCategories} from '../lib/categories.mjs';
import {tripSignals} from '../lib/signals.mjs';
import {renderScoreLine} from './score-line.mjs';
import {enrichPoint,sampleMunicipalPoint} from '../lib/geography-core.mjs';
import {nextMadridMorning,randomMadridLocalDateTime} from './random-datetime.mjs';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import '@fontsource-variable/manrope';
import './style.css';

const $=selector=>document.querySelector(selector);
const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&gt;','>':'&lt;','"':'&quot;',"'":'&#39;'}[char]));
const pct=value=>`${Math.round(value*100)}%`;
const money=value=>`$${value.toFixed(6)}`;
const types={airport_terminal:'Airport terminal',aerodrome:'Airport grounds',hospital:'Hospital',clinic:'Clinic',education:'University or campus',college:'College',school:'School',railway_station:'Railway station',station_building:'Station building',bus_station:'Bus terminal',zoo:'Zoo',theme_park:'Theme park',museum:'Museum',attraction:'Attraction',water_park:'Water park'};
const places=[
 {name:'Chamberí',coordinates:[40.4355,-3.7035]},{name:'Ciudad Universitaria',coordinates:[40.4489,-3.7294]},
 {name:'AZCA',coordinates:[40.4503,-3.6925]},{name:'Cuatro Torres',coordinates:[40.4778,-3.6888]},
 {name:'Atocha',coordinates:[40.4067,-3.6893]},{name:'Terminal 4',coordinates:[40.4918,-3.593]},
 {name:'Chamartín',coordinates:[40.4721,-3.6823]},{name:'Hospital La Paz',coordinates:[40.4814,-3.687]},
 {name:'Zoo Aquarium',coordinates:[40.409,-3.764]},{name:'Parque de Atracciones',coordinates:[40.412,-3.75]},
 {name:'Parque Warner',coordinates:[40.23,-3.594]}
];

async function initialize(){
 const started=performance.now();
 const geography=await fetch('/data/geography.json').then(response=>response.ok?response.json():null).catch(()=>null);
 const geoLoadMs=performance.now()-started;
 let categories=structuredClone(defaultCategories),trip,busy=false,target='origin',markers=[],line,lastResult=null;

 $('#app').innerHTML=`<header class="topbar"><a href="/" class="wordmark"><svg viewBox="0 0 28 28" aria-hidden="true"><path d="M5 22V6l9 8 9-8v16"/><circle cx="14" cy="14" r="2"/></svg><span>Ride-Hailing <b>Lab</b></span></a><div class="topmeta"><span class="status-dot"></span> Jev 1.13 <span class="divider">/</span><span>Interactive experiment</span></div></header>
 <main><div class="intro"><h1>Can Jev Understand a Trip?</h1><button class="quiet" id="random">Random trip in Madrid and evaluate</button></div>
 <div class="workspace"><section class="controls" aria-labelledby="scenario-title"><div class="section-heading"><h2 id="scenario-title">Your scenario</h2><span class="tag">Synthetic</span></div>
 <label for="when">Local date and time · Madrid</label><input id="when" type="datetime-local" required>
 <div class="route-fields"><div class="route-label"><span class="point a">A</span><label for="origin">Origin</label><button class="text-button" data-pick="origin">Pick on map</button></div><select id="origin">${places.map((place,index)=>`<option value="${index}">${place.name}</option>`).join('')}<option value="custom">Selected point</option></select>
 <div class="route-label"><span class="point b">B</span><label for="destination">Destination</label><button class="text-button" data-pick="destination">Pick on map</button></div><select id="destination">${places.map((place,index)=>`<option value="${index}">${place.name}</option>`).join('')}<option value="custom">Selected point</option></select><button id="swap" class="text-button swap">Swap origin and destination</button></div>
 <details id="context"><summary>Automatic geographic context</summary><p id="signal-summary" class="hint"></p><div id="geo-summary"></div><p class="hint">Neighborhoods: <a href="https://geoportal.madrid.es/IDEAM_WBGEOPORTAL/dataset.iam?id=422fa235-762b-11e9-861d-ecb1d753f6e8">Madrid City Council</a>. POIs: <a href="https://www.openstreetmap.org/copyright">© OpenStreetMap · ODbL</a>. Local snapshot; POIs within 100 m and containing facilities, not passenger activity.</p></details>
 <details id="category-editor"><summary>Purpose categories · <span id="category-count">6</span></summary><p class="hint">Edit labels and descriptions. This exact list is sent to Jev (2–20 categories).</p><div id="category-list"></div><button id="add-category" class="quiet" type="button">Add category</button> <button id="reset-categories" class="text-button" type="button">Reset six defaults</button></details></section>
 <section class="map-area" aria-label="Interactive Madrid map"><div class="map-toolbar"><span id="map-action"><b>A</b> Click to choose the origin</span><button id="fit" class="text-button">Fit</button></div><div id="map" tabindex="0" aria-label="Map. You can also choose points from the origin and destination lists."></div><div class="map-footer"><span><i class="line-key"></i> Straight connection, not a road route</span><span id="coords"></span></div></section>
 <section class="results" aria-labelledby="results-title"><div class="section-heading"><h2 id="results-title">Prediction</h2><span id="result-status" class="tag">Not evaluated</span></div><div class="run-area"><button id="evaluate" class="primary">Evaluate with Jev <span aria-hidden="true">→</span></button><p>1 trip · 3 questions · one real call</p><p id="error" class="error" role="alert" hidden></p></div><div id="result-body" aria-live="polite"><div class="empty"><svg viewBox="0 0 100 90" aria-hidden="true"><path d="M18 68C18 26 78 65 78 20"/><circle cx="18" cy="68" r="7"/><circle cx="78" cy="20" r="7"/></svg><h3>Context changes the reading.</h3><p>Choose two points and evaluate the trip to see purpose, willingness to pay, and willingness to wait.</p></div></div><div class="result-note">The most likely submitted purpose is shown even at low probability. “Other” means another likely purpose, not uncertainty. Probabilities are not calibrated for real passengers.</div></section></div>
 <section class="context-box" aria-labelledby="context-box-title"><h2 id="context-box-title">Context sent to Jev</h2><p class="hint">The exact natural-language situation from the last completed evaluation. Purpose categories and questions are sent separately.</p><p id="evaluated-context" class="context-copy muted-context">No evaluation yet.</p></section>
 <section class="context-box" aria-labelledby="response-box-title"><h2 id="response-box-title">Response from Jev</h2><p class="hint">The validated typed response from the same completed evaluation.</p><pre id="jev-response" class="response-copy muted-context">No evaluation yet.</pre></section>
 <footer>Ride-Hailing Lab <span>PoC · No bookings or real prices</span><a href="https://docs.typesafe.ai/primitives" target="_blank" rel="noopener">How Jev responds ↗</a></footer></main>`;

 const map=L.map('map',{zoomControl:false,scrollWheelZoom:false,dragging:!L.Browser.mobile,touchZoom:false,minZoom:8,maxZoom:18}).setView([40.434,-3.703],12);
 L.control.zoom({position:'bottomright'}).addTo(map);new ResizeObserver(()=>map.invalidateSize({pan:false})).observe($('#map'));L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
 const pointName=point=>point.geo_context?.neighborhood||point.coordinates.map(value=>value.toFixed(4)).join(', ');
 function markStale(){if(lastResult){$('#result-status').textContent='Input changed';$('#result-status').className='tag stale';}refreshInput();}
 function setTarget(side){target=side;$('#map-action').innerHTML=`<b>${side==='origin'?'A':'B'}</b> Click to choose the ${side}`;document.querySelectorAll('[data-pick]').forEach(button=>button.classList.toggle('active',button.dataset.pick===side));}
 function renderMap(fit=false){markers.forEach(marker=>marker.remove());markers=[];line?.remove();const pairs=['origin','destination'].map((side,index)=>{const point=trip.current_trip[side];const icon=L.divIcon({className:`map-pin ${index?'destination':''}`,html:`<span><i>${index?'B':'A'}</i></span>`,iconSize:[34,42],iconAnchor:[17,38]});const marker=L.marker(point.coordinates,{icon,draggable:!busy,alt:`${index?'Destination':'Origin'}: ${pointName(point)}`}).addTo(map);marker.bindTooltip(pointName(point),{direction:'top',offset:[0,-35]});marker.on('dragend',()=>choosePoint(side,marker.getLatLng()));markers.push(marker);return point.coordinates;});line=L.polyline(pairs,{color:'#285e4a',weight:3,dashArray:'7 7',opacity:.65}).addTo(map);if(fit)map.fitBounds(pairs,{padding:[70,70],maxZoom:13});$('#coords').textContent=pairs.map(point=>point.map(value=>value.toFixed(3)).join(', ')).join(' → ');}
 function facilityMarkup(context,geo){const seen=new Set();const pois=[...(context.important_pois||[]),...(geo.nearby||[]).filter(item=>item.name).map(item=>({...item,type:Object.entries(item.tags).map(([key,value])=>`${key}:${value}`).join(', '),relation:'nearby'}))].filter(item=>{const key=item.name.normalize('NFKC').toLowerCase();if(seen.has(key))return false;seen.add(key);return true;}).slice(0,12);return `<div class="poi-summary"><h3>Named POIs · inside or within 100 m</h3>${pois.length?pois.map(item=>`<p><b>${esc(item.name)}</b><br>${esc(types[item.type]||item.type)} · ${item.relation==='inside'?'Inside facility':`${item.distance_m} m`}${item.tags.opening_hours?`<br><small>OSM opening hours: ${esc(item.tags.opening_hours)} · opening status not interpreted</small>`:''}</p>`).join(''):'<p class="hint">No matching POIs in this snapshot; this does not prove absence.</p>'}<p class="hint">Up to 12 named places: containing facilities and point POIs. Distances are to a boundary or OSM node/center; they do not prove use.</p></div>`;}
 function statisticsMarkup(stat){const rows=[['mean_age','Mean age','years',1],['household_size','Household size','people / household',2],['net_income_household','Mean net household income','€ / household / year',0]];return `<div class="area-stats"><h3>Area statistics</h3>${rows.map(([key,label,unit,digits])=>{const metric=stat?.metrics[key];if(!metric||metric.value==null)return `<p>${label}: <b>Unavailable</b></p>`;return `<p><span>${label}</span><b>${Number(metric.value).toLocaleString('en',{maximumFractionDigits:digits,minimumFractionDigits:digits})} ${unit}</b><small>${esc(metric.geography==='distrito'?'District ':'Neighborhood ')}${esc(metric.area_name)} · ${esc(metric.reference)} · <a href="${esc(metric.source_url)}" target="_blank" rel="noopener">Source</a></small></p>`}).join('')}<p class="hint">Area averages, not passenger data. Household is not family; income is not wealth.</p></div>`;}
 function updateGeo(){const started=performance.now();for(const side of ['origin','destination'])trip.current_trip[side]=enrichPoint(trip.current_trip[side].coordinates,geography);const lookupMs=performance.now()-started;$('#geo-summary').innerHTML=['origin','destination'].map(side=>{const point=trip.current_trip[side],context=point.geo_context;const status={resolved:'Context available',partial:'Partial coverage',unavailable:'Context unavailable',outside_coverage:'Outside coverage'}[context.status];return `<p><b>${side==='origin'?'A · Origin':'B · Destination'}: ${esc(pointName(point))}</b><br>${esc(context.district||'District not identified')} · ${esc(status)}<br><span class="hint">Selected point · POIs within 100 m and containing facilities</span></p>${facilityMarkup(point.facility_context,context)}${statisticsMarkup(point.area_statistics)}`}).join('')+`<p class="hint">Snapshot: ${geography?esc(new Date(geography.retrievedAt).toLocaleString('en-GB')):'unavailable'} · OSM: ${geography?esc(geography.osmTimestamp):'—'}<br>Local lookup: ${lookupMs.toFixed(1)} ms · initial load: ${geoLoadMs.toFixed(0)} ms. Independent of Jev time.</p>`;}
 function choosePoint(side,latlng){if(busy)return;trip.current_trip[side]={coordinates:[+latlng.lat.toFixed(5),+latlng.lng.toFixed(5)]};$(`#${side}`).value='custom';updateGeo();renderMap();setTarget(side==='origin'?'destination':'origin');markStale();}
 map.on('click',event=>choosePoint(target,event.latlng));
 function editorTrip(){const next=structuredClone(trip);next.current_trip.request_local_datetime=$('#when').value;return next;}
 function refreshInput(){const current=editorTrip(),signals=tripSignals(current.current_trip);const holidays=[signals.calendar.destination.national.name,signals.calendar.destination.regional.name,signals.calendar.destination.local.name].filter(Boolean).join(', ')||'No known holiday';$('#signal-summary').textContent=`${signals.straight_line_distance.km.toLocaleString('en')} km straight line · ${signals.weekend?'Weekend':'Weekday'} · Destination: ${holidays}${Object.values(signals.calendar.destination).some(value=>value?.status==='unknown')?' (partial coverage or unsupported year)':''}`;}
 function setTrip(origin,destination,datetime=$('#when')?.value||'2026-09-22T07:45'){trip={case_id:'demo',current_trip:{request_local_datetime:datetime,time_zone:'Europe/Madrid',origin:{coordinates:origin},destination:{coordinates:destination}}};$('#when').value=datetime;$('#origin').value='custom';$('#destination').value='custom';updateGeo();renderMap(true);markStale();}
 function randomTrip(){const origin=sampleMunicipalPoint(geography);let destination;do{destination=sampleMunicipalPoint(geography);}while(origin[0]===destination[0]&&origin[1]===destination[1]);setTrip(origin,destination,randomMadridLocalDateTime());}
 function renderCategories(){$('#category-count').textContent=categories.length;$('#category-list').innerHTML=categories.map((category,index)=>`<fieldset class="category-row"><legend>Category ${index+1}</legend><label for="cat-${index}">Name</label><input id="cat-${index}" data-cat="${index}" data-field="label" maxlength="64" value="${esc(category.label)}"><label for="desc-${index}">Description</label><textarea id="desc-${index}" data-cat="${index}" data-field="description" maxlength="600">${esc(category.description)}</textarea><button type="button" class="text-button" data-delete="${index}">Remove category ${index+1}</button></fieldset>`).join('');$('#category-list').querySelectorAll('textarea').forEach(textarea=>{textarea.style.height='auto';textarea.style.height=`${textarea.scrollHeight}px`;});}
 $('#category-list').oninput=event=>{if(event.target.dataset.cat===undefined)return;categories[+event.target.dataset.cat][event.target.dataset.field]=event.target.value;if(event.target.tagName==='TEXTAREA'){event.target.style.height='auto';event.target.style.height=`${event.target.scrollHeight}px`;}markStale();};
 $('#category-list').onclick=event=>{if(event.target.dataset.delete===undefined||busy)return;categories.splice(+event.target.dataset.delete,1);renderCategories();markStale();};
 $('#add-category').onclick=()=>{if(categories.length>=20)return;categories.push({id:`custom_${crypto.randomUUID().replaceAll('-','')}`,label:`New category ${categories.length+1}`,description:''});renderCategories();markStale();};
 $('#reset-categories').onclick=()=>{categories=structuredClone(defaultCategories);renderCategories();markStale();};
 $('#category-editor').ontoggle=()=>{if($('#category-editor').open)renderCategories();};
 function distribution(probabilities,labels={}){return `<div class="distribution">${Object.entries(probabilities).sort((a,b)=>b[1]-a[1]).map(([name,value])=>`<div class="dist-row"><span>${esc(labels[name]||name)}</span><div class="track"><i style="width:${Math.max(0,Math.min(100,value*100))}%"></i></div><b>${pct(value)}</b></div>`).join('')}</div>`;}
 function renderResult(data){lastResult=data;const result=data.cases[0],labels=Object.fromEntries(data.evaluatedContext.categories.map(category=>[category.id,category.label]));$('#evaluated-context').textContent=data.evaluatedContext.trip;$('#jev-response').textContent=JSON.stringify(data.providerResponse,null,2);$('#result-status').textContent='Real response';$('#result-status').className='tag success';$('#result-body').innerHTML=`<div class="prediction-main"><span class="result-label">Most likely purpose</span><div class="purpose-title"><h3>${esc(labels[result.purpose.label]||result.purpose.label)}</h3><span>${pct(result.purpose.probability)}</span></div><p class="prediction-confidence">Confidence ${pct(result.purpose.confidence)}</p>${distribution(result.purpose.probabilities,labels)}</div>${[['willingness_to_pay','Willingness to pay'],['willingness_to_wait','Willingness to wait']].map(([key,label])=>`<div class="score-block"><div class="score-heading"><h3>${label}</h3><span class="prediction-confidence">Confidence ${pct(result[key].confidence)}</span></div>${renderScoreLine(result[key].score,'Low','High')}<details><summary>Probabilities</summary>${distribution(result[key].probabilities)}</details></div>`).join('')}<div class="metrics"><div><span>Jev time</span><b>${(data.latencyMs/1000).toFixed(2)} s</b></div><div><span>Estimated cost</span><b>${money(data.estimatedCostUsd)}</b></div></div><p class="usage">${data.usage.input_tokens.toLocaleString('en')} input tokens · ${esc(data.model)}<br>Full evaluation · ${data.questionCount} questions · USD, not an invoice<br>Browser round trip: ${(data.browserRoundTripMs/1000).toFixed(2)} s</p><div class="attributes">${data.attributes.demo?.night?'<span class="tag">Night</span>':''}${data.attributes.demo?.airport?'<span class="tag">Airport</span>':''}</div>${data.roundingDifferences.length?'<p class="hint">The provider score slightly differs from the displayed probability mean. The provider score is retained.</p>':''}`;}
 function setBusy(value){busy=value;$('#fit').disabled=value;$('#evaluate').disabled=value;$('#random').disabled=value;$('#evaluate').innerHTML=value?'<span class="spinner"></span> Asking Jev…':'Evaluate with Jev <span aria-hidden="true">→</span>';document.querySelectorAll('.controls input,.controls select,.controls textarea,.controls button').forEach(element=>element.disabled=value);markers.forEach(marker=>value?marker.dragging.disable():marker.dragging.enable());}
 async function evaluateCurrent(){if(busy)return;try{const current=editorTrip();if(!current.current_trip.request_local_datetime)throw Error('Choose a local date and time.');const submitted=validateCategories(categories);setBusy(true);const started=performance.now(),response=await fetch('/api/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trips:[current],categories:submitted})}),data=await response.json();if(!response.ok)throw Error(data.error||'Could not evaluate this trip.');data.browserRoundTripMs=performance.now()-started;renderResult(data);}catch(error){$('#error').textContent=error.message;$('#error').hidden=false;}finally{setBusy(false);}}
 $('#evaluate').onclick=evaluateCurrent;
 $('#random').onclick=()=>randomizeAndEvaluate({isBusy:()=>busy,validate:()=>validateCategories(categories),randomize:randomTrip,evaluate:evaluateCurrent,onError:error=>{$('#error').textContent=error.message;$('#error').hidden=false;}});
 $('#when').oninput=markStale;
 for(const side of ['origin','destination'])$(`#${side}`).onchange=event=>{if(event.target.value==='custom')return setTarget(side);const place=places[+event.target.value];trip.current_trip[side]={coordinates:structuredClone(place.coordinates)};updateGeo();renderMap(true);markStale();};
 document.querySelectorAll('[data-pick]').forEach(button=>button.onclick=()=>setTarget(button.dataset.pick));$('#fit').onclick=()=>renderMap(true);$('#swap').onclick=()=>{[trip.current_trip.origin,trip.current_trip.destination]=[trip.current_trip.destination,trip.current_trip.origin];updateGeo();renderMap(true);markStale();};
 renderCategories();setTrip(places[4].coordinates,places[5].coordinates,nextMadridMorning());setTarget('origin');evaluateCurrent();
}
initialize().catch(()=>{$('#app').innerHTML='<main><h1>Could not load the demo.</h1><p>Reload the page to try again.</p></main>';});
